# markdownlint-cli2 configuration for dotnet-agent-harness
# RuleSync-aware markdown linting

config:
  default: true
  # Line length - too strict for technical documentation
  MD013: false
  # Duplicate headings - skills have similar sections (Workflow, References, etc.)
  MD024:
    siblings_only: true
  # Inline HTML - needed for tables and special formatting
  MD033: false
  # Bare URLs - common in knowledge sources and references
  MD034: false
  # First line must be heading - frontmatter blocks this
  MD041: false
  # No trailing spaces - but allow in markdown for line breaks
  MD009:
    strict: false
  # No hard tabs
  MD010: true
  # Heading styles must be consistent
  MD003:
    style: atx
  # Ordered list item prefix
  MD029:
    style: ordered
  # Spaces after list markers
  MD030: true
  # Fenced code blocks should have language
  MD040: true
  # Code block style - fenced only
  MD046:
    style: fenced
  # File should end with a single newline
  MD047: true
  # Code fences should be surrounded by blank lines
  MD031: true
  # Lists should be surrounded by blank lines
  MD032: true
  # Heading levels should only increment by one level at a time
  MD001: true

ignores:
  - "node_modules/**"
  - ".opencode/**"
  - ".claude/**"
  - ".github/agents/**"
  - ".github/instructions/**"
  - ".github/prompts/**"
  - ".github/skills/**"
  - ".codex/**"
  - ".gemini/**"
  - ".agents/**"
  - ".agent/**"
  - "dist/**"
  - "packages/opencode-plugin/bundled/**"
